### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by jav1988** [X3NNY/sstilabs#1]
PS E:\VSCode\CTF\03丨学习测试\SSTI\sstilabs-master\flasklab> python app.py
Traceback (most recent call last):
  File "E:\VSCode\CTF\03丨学习测试\SSTI\sstilabs-master\flasklab\app.py", line 10, in <module>
    from flask import Flask, request, render_template, render_template_string
  File "C:\Python310\lib\site-packages\flask\__init__.py", line 14, in <module>
    from jinja2 import escape
  File "C:\Python310\lib\site-packages\jinja2\__init__.py", line 12, in <module>
    from .environment import Environment
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "C:\Python310\lib\site-packages\jinja2\defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "C:\Python310\lib\site-packages\jinja2\filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (C:\Python310\lib\site-packages\markupsafe\__init__.py)
这个报错是为什么？

**Comment by jav1988** [comment]
update it!
```shell
pip install --upgrade Flask Jinja2
```

**Comment by sw3rt** [comment]
最好和flask的版本兼容
